### ISSUE TITLE
not able to change local briefs

### ISSUE THREAD

**Issue by gpsloco** [capttaco/Briefs#1]
Hi, any chance that you tell us where to change the local briefs? Also, what is needed to compile the compacts app?

Thank you, Tilman

**Comment by capttaco** [comment]
To Add Local Briefs:

First add the folder containing your desired brief into the Xcode project, then inside the Briefs.app target, make sure the folder is copied into the resources bundle.

**Comment by capttaco** [comment]
To compile compact-briefs:

Change the active target to the compacter (also change the framework used to either the 10.6 or 10.5 SDK) and build. Then go into build folder and run the command from Terminal, with the path of the brief to compact and the desired output name (and path).

**Comment by Clarko** [comment]
Out of interest, do we even need to use the compacter? Or is that only useful for source obfuscation? I've built with an uncompacted Briefslist and it works pretty happily in the sim.
